# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlutterCombine' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  flutter_application_path = './my_flutter'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  
  use_frameworks!
    install_all_flutter_pods(flutter_application_path)

  # Pods for FlutterCombine

  target 'FlutterCombineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterCombineUITests' do
    # Pods for testing
  end

end
