# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewFireBase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewFireBase
  pod 'Firebase/Core'
	pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'GoogleAnalytics'


  target 'NewFireBaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewFireBaseUITests' do
    # Pods for testing
  end

end
