# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'Firebase/Crashlytics'

	# Recommended: Add the Firebase pod for Google Analytics
	pod 'Firebase/Analytics'
  
  pod 'Firebase'
  pod 'Firebase/InAppMessaging'
  # Pods for FirebaseTest

  target 'FirebaseTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseTestUITests' do
    # Pods for testing
  end

end
